name: Email_Workflow_Forecasts_summary

on:
  workflow_run:
    workflows: ["Generate_RespiCast_Forecasts"]
    types:
      - completed

jobs:
  notify_job:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository to access files
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Send an email with attached files
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          # Email server details (SMTP)
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}

          # Email content
          subject: "Workflow Completed: Generate RespiCast Forecasts"
          to: recipient@example.com
          from: ${{ secrets.EMAIL_USERNAME }}
          content_type: text/html
          body: |
            <p>Hello,</p>
            <p>The workflow <b>Generate_RespiCast_Forecasts</b> has completed successfully.</p>
            <p>Attached are the relevant files:</p>

          # Attach specific files
          attachments: |
            ./models/Forecasting-hubs_models/model_output/Syndromic_indicators/2024-12-04-ECDC-soca_simplex.csv
            ./models/Forecasting-hubs_models/model_output/Syndromic_indicators/2024-12-04-ECDC-SARIMA.csv
